### PR TITLE
Class Diagram: Adjust spacing of newly added lines to a class

### LINKED ISSUE #333: Weird spacing in classes, enums between lines
### Describe the bug
Apollon has a weird spacing between the lines of constants in enums/parameters in classes.

#### To Reproduce

1. Go to Apollon
2. Add an enum/class/etc
3. Add constants/parameters

#### Expected behavior

even spacing between lines

#### Screenshots

image
image
image

### Environment

<details><pre>
 - OS: Win11
 - Browser chrome
 - Version Apollon: 2.0.0, Chrome: Version 119.0.6045.200 (Official Build) (64-bit)
</pre></details>

### PR DESCRIPTION
**Pull request by farisd16**
### Checklist
- ~~[ ] I documented the TypeScript code using JSDoc style.~~
- [x] I added multiple screenshots/screencasts of my UI changes
- ~~[ ] I translated all the newly inserted strings into German and English~~

### Motivation and Context
Fixes #333 

### Description
I have adjusted the height of newly added lines to a class to match the height of lines from the preview (specifically class-preview.ts)

### Steps for Testing
1. Create a class diagram
2. Add a new class
3. Add new lines (attribute, method, etc.) to the class 
4. Assert that all lines have even spacing

### Test Coverage
| File                                       | Branch | Line   |
| uml-classifier-member.ts | 100%    | 100% |

### Screenshots
Before:
image

After:
image

### CODE REVIEW

**Comment by FelixTJDietrich** [comment]
@farisd16 it is maybe a bit too much space now? Can you make it similar to Constant 4, Constant 5, Constant 6 in the before screenshot?

**Comment by farisd16** [comment]
> @farisd16 it is maybe a bit too much space now? Can you make it similar to Constant 4, Constant 5, Constant 6 in the before screenshot?

Sure, this is what it looks like:

image

**Comment by FelixTJDietrich** [comment]
Somehow the vertical padding is now smaller, don't you think?

**Review by FelixTJDietrich — APPROVED** [review]
Code changes look good to me and I could verify that the spacing looks correct now locally :)
image

**Comment by loreanvictor** [comment]
code looks good to me too, though I wonder if we need to manage these visual constants a bit better (perhaps in a follow-up issue).

**Pull request merged**
