### PR TITLE
[Feature] Extend uml and assessment component

### PR DESCRIPTION
**Pull request by Olimbia23**
### Checklist
- [X] I documented the TypeScript code using JSDoc style.
- [X] I added multiple screenshots/screencasts of my UI changes
- [X] I translated all the newly inserted strings into German and English

### Motivation and Context
This change is the part of the improving tutor training initiative. The idea is providing user more information about the incorrectly submitted assessment, in order to improve the overall training process.

### Description
1. I added a new warning icon above the UML node which indicates that this node has incorrect assessment. 
2. I also added in the assessment view a new text label describing the current validation status.
3. Added the possibility to delete an assessment just as we do in text feedback editor.

### Steps for Testing
1. Log in to Artemis
2. Navigate to Course Administration
3. Go to the Modeling Exercise Assessment Dashboard.
4. Start the training by assessing the example submission and then click the button submit assessment.

### Test Coverage
Assessment-Section.tsx: 93.26 %
Assessable.tsx: 80.66 %

### Screenshots
after1

### CODE REVIEW

**Review by Malyuk-A — APPROVED** [review]
Code looks good.

**Review by Malyuk-A — APPROVED** [review]
Now I also tested it locally. (After quite a while) It works as described 👍 (This review and PR are similar to the corresponding Artemis one)

**Review by Malyuk-A — APPROVED** [review]
re-approve

**Review by imstreetspirit — APPROVED** [review]
from my side, code changes make sense, tested the functionality. but I am not sure if the newly added strings cause coupling between  Artemis and Apollon. maybe @iozbeyli can say something about that.

**Comment by Olimbia23** [comment]
> from my side, code changes make sense, tested the functionality. but I am not sure if the newly added strings cause coupling between Artemis and Apollon. maybe @iozbeyli can say something about that.

Thank you a lot for reviewing the PR @imstreetspirit. I agree with your suggestion regarding the Artemis-Apollon coupling and I addressed it. 😀

**Comment by Olimbia23** [comment]
> Now I also tested it locally. (After quite a while) It works as described 👍 (This review and PR are similar to the corresponding Artemis one)

Thank you for testing it @Malyuk-A. I appreciate it 👼

**Review by Malyuk-A — APPROVED** [review]
re-approve (due to testing related/based-on PR locally again)

**Review by imstreetspirit — APPROVED** [review]
re-approve since the functionality is tested on ts1

**Pull request merged**
