### PR TITLE
`Development`: Fix issue for exporting manually layouted diagram

### PR DESCRIPTION
**Pull request by minrows**
### Checklist
- [x] I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
This PR fixes an issue with the cut-off of elements of a manually layouted diagram.

### Description
Issue Number: https://github.com/ls1intum/Apollon/issues/258

### Steps for Testing
1. Clone the repo
2. Checkout to branch `bugfix/export-fix`
3. Start the application by executing `yarn install` followed by `yarn start`
4. Insert any two elements and connect them in the canvas in a way that they have manual waypoint connectors (more than 2 edges).
5. Layout the connector manually
6. Export the diagram by clicking on the All button from Export Menu on side menu
7. Observe that all diagram elements are visible with no cut-off.

#### Before:
screen-capture (15)

#### After:
screen-capture (14)

### CODE REVIEW

**Review by akesfeden — COMMENTED** [review]
Tested on test server, export seems to work as expected however when I close and reopen the page the model seems shifted outside of the view:
What I draw:
image

After reload:
image

**Comment by minrows** [comment]
> Tested on test server, export seems to work as expected however when I reload the page the model seems shifted outside of the view: What I draw: image
> 
> After reload: image

Thank you for your feedback @akesfeden. 👍 
The shifting of the diagram while reloading is not brought up by this PR (checked and confirmed in the previous version).
The issue could be handled in follow-up PR.

**Review by akesfeden — APPROVED** [review]
Thanks for the explanation. In that case, the export works as described.

**Review by ge65cer — APPROVED** [review]
Tested locally, bug is fixed.

**Pull request merged**
