### PR TITLE
`Development`: Fix cropped out example solution in Artemis issue

### PR DESCRIPTION
**Pull request by minrows**
### Checklist
- [x] I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
This PR fixes the issue of cropped-out example solution in Artemis.
Issue: https://github.com/ls1intum/Artemis/issues/5639

### Steps for Testing
**This PR needs to be tested on Artemis.** 
- Deploy [this](https://bamboo.ase.in.tum.de/deploy/viewDeploymentVersion.action?versionId=535658515) version to one of the test server of Artemis
- Create new Modeling Exercises by going to administration > Exercises > Create new Modeling Exercise
- Fill out the necessary fields
- While setting the example solution, enter two elements into the canvas and connect them
- Layout the connector manually and save it
- Observe that the connector is not cropped out anymore in example solution section of the exercise preview page

#### Before
screen-capture (21)

#### After
screen-capture (22)

### CODE REVIEW

**Review by Santia-go — APPROVED** [review]
Tested on TS2
Working as expected
For some reason, there is necessary a hard refresh to update the view of the model. 

https://user-images.githubusercontent.com/88991954/189673512-72d86555-495f-4b2e-8f36-9088c65fc1a7.mov

**Comment by bassner** [comment]
For me, it changes the position of the connector after a reload. Intended?


https://user-images.githubusercontent.com/23171488/189682600-82bf3e21-0335-4787-b9ff-63bfbc156d1f.mov

**Comment by minrows** [comment]
> For me, it changes the position of the connector after a reload. Intended?
> 
>  Screen.Recording.2022-09-12.at.16.36.13.mov

Fixed in https://github.com/ls1intum/Apollon/pull/264/commits/7bdd14696343ccf82ebb42f1c635181859af9e54

**Review by bassner — APPROVED** [review]
Works now! LGTM 👍

**Review by akesfeden — APPROVED** [review]
Tested on TS2, works as described.

**Pull request merged**
