### PR TITLE
`Development`: Fix issue with interface marker while exporting diagram

### PR DESCRIPTION
**Pull request by minrows**
### Checklist
- [x] I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
The appearance of the required interface marker was not displayed correctly (as implemented by [PR ](https://github.com/ls1intum/Apollon/pull/263))when the diagram was exported (PDF, SVG, ...).
This PR fixes an issue with the appearance of the required interface marker while exporting the diagram.

#### Local Machine

1. Clone the repository 
2. Checkout to the branch `bugfix/pdf-export-issue`
3. Start the application by executing `yarn install` followed by `yarn start` commands.
4. Select Component Diagram as DiagramType
5. Insert Interface and Component in the canvas
6. Connect component and interface using required interface connector.
7. Export the diagram by clicking on `All` from `Export menu`.
8. Observe that the semicircle marker is used as illustrated in the screenshot section. 

#### Testing Server

1. Goto [test server](https://test1.apollon.ase.in.tum.de/)
2. Create new Component Diagram by clicking on File > New > Component Diagram
3.  Insert Interface and Component in the canvas
4. Connect component and interface using required interface connector.
5. Export the diagram by clicking File > Export > As PDF (or any format).
6. Observe that the semicircle marker is used as illustrated in the screenshot section. 

#### Before
screen-capture (3)

#### After
screen-capture (4)

PS: Changes released in version [2.12.5-alpha.3](https://www.npmjs.com/package/@ls1intum/apollon/v/2.12.5-alpha.3)

### CODE REVIEW

**Review by akesfeden — APPROVED** [review]
Tested on test server, works as described. Code changes look reasonable.

**Comment by minrows** [comment]
> 

Seems like you're using the "Provided Interface" instead of "Required Interface".
Could you please use "required interface" instead?

**Comment by 4ludwig4** [comment]
Ah thanks, I didn't know how to get to the "required Interface". Just found out that I get there via double click.

Then it seems to be working except the boundary problem, but that's probably another problem?!

[ComponentDiagram (1).pdf](https://github.com/ls1intum/Apollon/files/9952069/ComponentDiagram.1.pdf)

**Comment by minrows** [comment]
Thanks @4ludwig4 . And yes, the other issue will be fixed in separate PR.

**Pull request merged**
