### PR TITLE
Bugfix/png cutoff

### PR DESCRIPTION
**Pull request by iozbeyli**
Adds 15px margin around svg export.
Flowchart

### CODE REVIEW

**Comment by krusche** [comment]
Great, you only need to fix the tests in the build

**Review by ivanchimeno — APPROVED** [review]
Looks good for me :+1:

**Review by SimonEntholzer — APPROVED** [review]
Yep, that looks better :+1:

**Review by FrankeLukas — APPROVED** [review]

**Review by FuchsDominik — APPROVED** [review]
Margin looks good

**Pull request merged**
