### PR TITLE
``Development``: Fix for coloring elements in Apollon

### PR DESCRIPTION
**Pull request by minrows**
### Checklist
- [x] I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
This PR fixes the issue with the filling the elements in Apollon.
Issue Number: https://github.com/ls1intum/Apollon/issues/232

### Steps for Testing
1. Goto to [test server](https://test1.apollon.ase.in.tum.de/)
2. Try filling the colors of elements as illustrated in Screenshots section

### Screenshots
screen-capture (2)

Todos:

- [x] Release beta version of Apollon from this branch
- [x] Point standalone to this newly created release
- [x] Deploy that standalone to test server

### CODE REVIEW

**Comment by martindevtum** [comment]
code looks good. will test once it is on the test server. 
did you check, wether the fills are also visible when exported as svg?

**Comment by minrows** [comment]
> code looks good. will test once it is on the test server. did you check, wether the fills are also visible when exported as svg?

Yes @martindevtum. Its working as expected.

**Comment by minrows** [comment]
Its now deployed in [test server](https://test1.apollon.ase.in.tum.de/).

**Review by canberkanar — APPROVED** [review]
Tested on apollon-ts1 in the testing session. The bug was fixed and we were able to set different coloring for all elements both in the dark and light modes. Good job! 💪🏻

**Review by akesfeden — APPROVED** [review]
Tested on test1, fill colors are applied correctly, code changes also seem good.

**Review by pusll-genesis — APPROVED** [review]

**Review by 4ludwig4 — APPROVED** [review]
Tested during the monday test session and changing the color of the boxes, text and lines of the boxes worked on Firefox.

**Review by martindevtum — APPROVED** [review]

**Pull request merged**
