### PR TITLE
Add assessment highlight assessments apollon

### PR DESCRIPTION
**Pull request by nicolasruscher**
### Checklist
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes
- [x] I translated all the newly inserted strings into German and English

### Steps for Testing

1. ...

### CODE REVIEW

**Review by MDK5 — APPROVED** [review]
Reviewed code in testing session, looks good

**Review by coolchock — APPROVED** [review]
code looks good :+1:

**Review by lschlesinger — APPROVED** [review]
approved the code in the testing session

**Review by tobiasjungmann — APPROVED** [review]
Code looks good and colors make sense.

**Pull request merged**
