### PR TITLE
`Collaboration`: Highlight user interacting elements in real time collaboration

### PR DESCRIPTION
**Pull request by minrows**
# Motivation and Context
This PR enables highlighting user-interacting elements in Real Time Collaboration Mode. 

# Description

- Collaborators are assigned with unique color upon joining Real Time Collaboration Session
- That unique color is then used to highlight the elements they are interacting with, throughout the session for other collaborators.

# Screenshots
screen-capture (10)

# Todos:

- [x] Enable highlighting of elements by multiple users
- [x] Release alpha version (2.10.4-alpha.1)
- [x] Fix issue with displaying own name in highlighted elements

# Additional Info
Changes included in Release version: 2.10.4-alpha.1

### CODE REVIEW

**Review by TheTrueVester — APPROVED** [review]
Tested on apollon ts1 during testing session. Everything worked as expected.

**Review by babyygemperor — APPROVED** [review]
Tested on ts1 in a testing session, works as described

**Review by canberkanar — COMMENTED** [review]
Tested on Apollon Test Server 1 in the testing session. Name of user is displayed once they interact with an element but the label is removed as soon as the user interacts with another element.

Future improvement: Labels of user names interacting with an element can be ordered. Right now they are displayed in the order the interaction is made.

**Review by canberkanar — APPROVED** [review]
I really did not like the shortening of names after 7 characters. Santiago was not a really long name but we were not able to distinguish the users by their surnames. However this does not effect the functionality.

image

**Pull request merged**
